steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run' , 'build']
# Google Cloud doesn't natively support Git LFS, so we have to manually enable it
  - name: 'gcr.io/public-side-projects/git-lfs'
    args: ['install']
    dir: '/workspace'
  - name: 'gcr.io/public-side-projects/git-lfs'
    args: ['pull']
    dir: '/workspace'
# Deploy to the Google Cloud Storage bucket that serves the web app at https://zines.garrettheath4.com
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ["-m", "rsync", "-r", "-c", "-d", "./build", "gs://zines.garrettheath4.com"]
